### PR TITLE
Feature/ini parser

### PR DESCRIPTION
**Pull request by stewest**
Fixes: #1 With indigophp/ini

### CODE REVIEW

**Comment by bomoko** [comment]
@stewest , Interestingly - looking at the code, it seems that Indigophp\Ini's present implementation doesn't actually seem to provide the actual fallback implementation. 

I think we should use this -> https://github.com/matomo-org/component-ini

**Comment by stewest** [comment]
@bomoko Switched to Matomo Ini

**Comment by stewest** [comment]
Let me know if you need me to do anything else @bomoko

**Comment by bomoko** [comment]
Finally merged @stewest! Sorry it took so long.

**Comment by stewest** [comment]
awesome

**Pull request merged**
