### PR TITLE
Allow nette/finder ^2.5 alongside ^3.0@dev

### PR DESCRIPTION
**Pull request by mitrpaka**
nette/finder latest stable version is 2.5.1, which equals with 3.0@dev branch. Please allow nette/finder latest released version alongside with 3.0@dev in order to prevent composer dependency issues that are caused by explicit ^3.0@dev requirement.

### CODE REVIEW

**Comment by stewest** [comment]
Hi @mitrpaka , thanks, we'll take a look!

**Comment by kitzberger** [comment]
@bomoko, to actually use this package as a dependency it would be great if there was a new release/tag that we could use instead of `dev-master`. Could you please add a new tag? ;-)

**Comment by bomoko** [comment]
oops, huge apologies @kitzberger - 0.0.3 released

Thanks for pinging me on this.

**Comment by kitzberger** [comment]
Yeah, thanks!!!

**Pull request merged**
